#
# Copyright (C) 2007 Freescale Semiconductor, Inc. All rights reserved.
#
# Author: Zhang Wei, wei.zhang@freescale.com, Jun 2007
#
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

obj-$(CONFIG_RIO_SA_DEFAULT_BITMAP) += bitmap.o
