# DAVINCI Platform Support
snd-soc-davinci-objs := davinci-pcm.o
snd-soc-davinci-i2s-objs := davinci-i2s.o

obj-$(CONFIG_SND_DAVINCI_SOC) += snd-soc-davinci.o
obj-$(CONFIG_SND_DAVINCI_SOC_I2S) += snd-soc-davinci-i2s.o
obj-$(CONFIG_SND_DAVINCI_SOC_I2S_MCBSP) += davinci-i2s-mcbsp.o
obj-$(CONFIG_SND_DAVINCI_SOC_I2S_MCASP) += davinci-i2s-mcasp.o
obj-$(CONFIG_SND_DAVINCI_SOC_I2S_VCIF) += davinci-i2s-vcif.o

# DAVINCI Machine Support
snd-soc-evm-objs := davinci-evm.o

obj-$(CONFIG_SND_DM644X_SOC_EVM) += snd-soc-evm.o
obj-$(CONFIG_SND_DM357_SOC_EVM) += snd-soc-evm.o
obj-$(CONFIG_SND_DM355_SOC_EVM) += snd-soc-evm.o
obj-$(CONFIG_SND_DM365_SOC_EVM) += snd-soc-evm.o
obj-$(CONFIG_SND_DM6467_SOC_EVM) += snd-soc-evm.o
obj-$(CONFIG_SND_DA8XX_SOC_EVM) += da8xx-evm.o
