# LTT facilities makefile

obj-$(CONFIG_LTT)			+= ltt-facility-loader-core.o
obj-$(CONFIG_LTT_FACILITY_FS)		+= ltt-facility-loader-fs.o
obj-$(CONFIG_LTT_FACILITY_FS_DATA)		+= ltt-facility-loader-fs_data.o
obj-$(CONFIG_LTT_FACILITY_IPC)		+= ltt-facility-loader-ipc.o
obj-$(CONFIG_LTT_FACILITY_KERNEL_ARCH)	+= \
			ltt-facility-loader-kernel_arch_$(ARCH).o
obj-$(CONFIG_LTT_FACILITY_KERNEL)	+= ltt-facility-loader-kernel.o
obj-$(CONFIG_LTT_FACILITY_MEMORY)	+= ltt-facility-loader-memory.o
obj-$(CONFIG_LTT_FACILITY_NETWORK)	+= ltt-facility-loader-network.o
obj-$(CONFIG_LTT_FACILITY_PROCESS)	+= ltt-facility-loader-process.o
obj-$(CONFIG_LTT_FACILITY_SOCKET)	+= ltt-facility-loader-socket.o
obj-$(CONFIG_LTT_FACILITY_TIMER)	+= ltt-facility-loader-timer.o
obj-$(CONFIG_LTT_FACILITY_STATEDUMP)	+= ltt-facility-loader-statedump.o
obj-$(CONFIG_LTT_FACILITY_STACK)	+= ltt-facility-loader-stack.o
obj-$(CONFIG_LTT_FACILITY_NETWORK_IP_INTERFACE)	+= \
			ltt-facility-loader-network_ip_interface.o

