# LTT probes makefile

obj-$(CONFIG_LTT_PROBE_FS)		+= ltt-probe-fs.o
obj-$(CONFIG_LTT_PROBE_ARCH)	+= \
			ltt-probe-$(ARCH).o
obj-$(CONFIG_LTT_PROBE_IPC)		+= ltt-probe-ipc.o
obj-$(CONFIG_LTT_PROBE_KERNEL)	+= ltt-probe-kernel.o
obj-$(CONFIG_LTT_PROBE_LIST)	+= ltt-probe-list.o
obj-$(CONFIG_LTT_PROBE_MM)	+= ltt-probe-mm.o
obj-$(CONFIG_LTT_PROBE_NET)	+= ltt-probe-net.o
